//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.14 at 07:10:51 AM EDT 
//


package com.gobucket.httpfeeder.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ZID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="item" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="couponid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="activedate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shutoff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="expiration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="majorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="minorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="geotarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pid",
    "nid",
    "zid",
    "item"
})
@XmlRootElement(name = "coupons")
public class Coupons {
	
	
    @XmlElement(name = "PID")
    protected int pid;
    @XmlElement(name = "NID")
    protected int nid;
    @XmlElement(name = "ZID", required = true)
    protected String zid;
    @XmlElement(required = true)
    protected List<Coupons.Item> item;

    
    public Coupons() {
	}

	/**
     * Gets the value of the pid property.
     * 
     */
    public int getPID() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     */
    public void setPID(int value) {
        this.pid = value;
    }

    /**
     * Gets the value of the nid property.
     * 
     */
    
    public int getNID() {
        return nid;
    }

    /**
     * Sets the value of the nid property.
     * 
     */
    public void setNID(int value) {
        this.nid = value;
    }

    /**
     * Gets the value of the zid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getZID() {
        return zid;
    }

    /**
     * Sets the value of the zid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZID(String value) {
        this.zid = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coupons.Item }
     * 
     * 
     */
    
    public List<Coupons.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Coupons.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="couponid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="activedate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shutoff" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="expiration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="majorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="minorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="geotarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "couponid",
        "link",
        "description",
        "image",
        "activedate",
        "shutoff",
        "expiration",
        "majorCategory",
        "minorCategory",
        "brand",
        "value",
        "geotarget"
    })
    public static class Item {

        protected Long couponid;
        @XmlElement(required = true)
        protected String link;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String image;
        @XmlElement(required = true)
        protected String activedate;
        @XmlElement(required = true)
        protected String shutoff;
        @XmlElement(required = true)
        protected String expiration;
        @XmlElement(required = true)
        protected String majorCategory;
        @XmlElement(required = true)
        protected String minorCategory;
        @XmlElement(required = true)
        protected String brand;
        protected int value;
        protected int geotarget;

        
        
        public Item() {
		}

		/**
         * Gets the value of the couponid property.
         * 
         */
        
        public Long getCouponid() {
            return couponid;
        }

        /**
         * Sets the value of the couponid property.
         * 
         */
        public void setCouponid(Long value) {
            this.couponid = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the image property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImage(String value) {
            this.image = value;
        }

        /**
         * Gets the value of the activedate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getActivedate() {
            return activedate;
        }

        /**
         * Sets the value of the activedate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivedate(String value) {
            this.activedate = value;
        }

        /**
         * Gets the value of the shutoff property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getShutoff() {
            return shutoff;
        }

        /**
         * Sets the value of the shutoff property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShutoff(String value) {
            this.shutoff = value;
        }

        /**
         * Gets the value of the expiration property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getExpiration() {
            return expiration;
        }

        /**
         * Sets the value of the expiration property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpiration(String value) {
            this.expiration = value;
        }

        /**
         * Gets the value of the majorCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getMajorCategory() {
            return majorCategory;
        }

        /**
         * Sets the value of the majorCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMajorCategory(String value) {
            this.majorCategory = value;
        }

        /**
         * Gets the value of the minorCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getMinorCategory() {
            return minorCategory;
        }

        /**
         * Sets the value of the minorCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMinorCategory(String value) {
            this.minorCategory = value;
        }

        /**
         * Gets the value of the brand property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        
        public String getBrand() {
            return brand;
        }

        /**
         * Sets the value of the brand property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrand(String value) {
            this.brand = value;
        }

        /**
         * Gets the value of the value property.
         * 
         */
        
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the geotarget property.
         * 
         */
        
        public int getGeotarget() {
            return geotarget;
        }

        /**
         * Sets the value of the geotarget property.
         * 
         */
        public void setGeotarget(int value) {
            this.geotarget = value;
        }

		@Override
		public String toString() {
			return "Item [couponid=" + couponid + ", link=" + link + ", description=" + description + ", image=" + image
					+ ", activedate=" + activedate + ", shutoff=" + shutoff + ", expiration=" + expiration
					+ ", majorCategory=" + majorCategory + ", minorCategory=" + minorCategory + ", brand=" + brand
					+ ", value=" + value + ", geotarget=" + geotarget + "]";
		}
        
    }


	@Override
	public String toString() {
		return "Coupons [pid=" + pid + ", nid=" + nid + ", zid=" + zid + ", item=" + item + "]";
	}

}
